##  **numpy library** 

In [2]:
import numpy as np

### Creating an array from numpy

In [3]:
arr = np.array([1,2,30,-4,5])
arr 

array([ 1,  2, 30, -4,  5])

### Array to list/ string / byte string / binary file

In [4]:
arr.tolist()

[1, 2, 30, -4, 5]

In [5]:
arr.tostring()

/tmp/ipykernel_1843/2127459365.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  arr.tostring()


b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x1e\x00\x00\x00\x00\x00\x00\x00\xfc\xff\xff\xff\xff\xff\xff\xff\x05\x00\x00\x00\x00\x00\x00\x00'

In [6]:
arr.tobytes() # order is an optional argument, default values =  C, A, K, F

b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x1e\x00\x00\x00\x00\x00\x00\x00\xfc\xff\xff\xff\xff\xff\xff\xff\x05\x00\x00\x00\x00\x00\x00\x00'

In [7]:
arr.tofile('arr.dat') # numpy arrays to binary file

### Array basic operations

In [8]:
arr.ndim # dimension of array

1

In [9]:
np.ndim(arr) # dimension of array

1

In [10]:
arr.size # no. of elements in array 

5

In [11]:
arr.__len__() # no. of elements in array

5

In [12]:
arr.dtype   # data type of the array 

dtype('int64')

In [13]:
arr.itemsize # byte space to save one element of the array

8

In [14]:
arr.nbytes # array's total space in bytes

40

In [15]:
arr.shape # shape of the array

(5,)

In [16]:
'''  Summation of array elements
args :
    axis : 0 (row) / 1 (column)  # 0 for 1D / Default
'''
arr.sum()

34

In [17]:
arr.cumsum() # cumulative sum

array([ 1,  3, 33, 29, 34])

In [18]:
arr.cumprod() # cumulative product

array([    1,     2,    60,  -240, -1200])

In [19]:
arr.mean() # mean of array  

6.8

In [20]:
arr.prod() # product of the array elements

-1200

In [21]:
arr1 = np.array([[4, 5, 6],[7, 8, 9]])
arr1.diagonal()  # returns the diagonal array (read only)

array([4, 8])

In [22]:
arr.std() # stddev of array 

11.956588142108098

In [23]:
arr.var() # variance of array     

142.95999999999998

In [24]:
arr.max() # max of array    

30

In [25]:
arr.min() # min of array    

-4

In [26]:
arr.argmax() # index of max of array

2

In [27]:
arr.argmin() # index of min of array

3

In [28]:
arr.argsort() # index of sorted array without changing array

array([3, 0, 1, 4, 2])

In [29]:
arr2 = arr.copy()  # deep copy of the array
arr2.sort()  # sorting the array
arr2

array([-4,  1,  2,  5, 30])

In [30]:
arr.byteswap() # Swap the bytes of the array elements 

array([  72057594037927936,  144115188075855872, 2161727821137838080,
       -216172782113783809,  360287970189639680])

In [31]:
arr.data  # memory location of array data

In [32]:
arr.view(np.int16) # view the array in different dtypes
# if arr d_type is big & u view into small d_type then extra space will filled with 0 or empty sets 

array([ 1,  0,  0,  0,  2,  0,  0,  0, 30,  0,  0,  0, -4, -1, -1, -1,  5,
        0,  0,  0], dtype=int16)

In [33]:
arr.strides  # no. of bytes space in memory between elements along axis

(8,)

In [34]:
arr.squeeze() # Remove axes of length one from array

array([ 1,  2, 30, -4,  5])

In [35]:
arr.ctypes  # c pointer for cython 

In [36]:
arr.copy() # make a deep copy (different copy of array on memory)

## by default arr object pass by value using = operator

array([ 1,  2, 30, -4,  5])

In [37]:
np.choose([0,2,4], arr)  # choose the specific elements from the array as other array

array([ 1, 30,  5])

In [38]:
a1 = np.array([0,2,4])  # array of indices of specific elements
a1.choose(arr) # choose the specific elements from the array as other array (deep copy)

array([ 1, 30,  5])

In [39]:
arr.clip(min = -3)  # check elements lies between range [-3, inf]

array([ 1,  2, 30, -3,  5])

In [40]:
arr.clip(max=15)  # check elements lies between range [-inf, 15]

# change the element into max or min val that lies outside of the range

array([ 1,  2, 15, -4,  5])

In [41]:
arr.clip(min = 0, max = 20) # check elements lies between range [0, 20]

array([ 1,  2, 20,  0,  5])

In [42]:
arr[2] = 0
arr.nonzero()  # indices of nonzero elements of array

(array([0, 1, 3, 4]),)

In [43]:
np.where(arr == 0)  # find indices of elements that meets the condition 

(array([2]),)

In [44]:
arr.searchsorted(6) # Find indices where elements of v should be inserted in a to maintain order.

5

In [45]:
a = arr.flat[2:4] # used for indexing & slicing (deep copy)
arr

array([ 1,  2,  0, -4,  5])

In [46]:
arr.item(2)  # getting element from the array

0

In [47]:
print(arr)
arr.itemset(2, -4)  # update element onto given index
print(arr)

[ 1  2  0 -4  5]
[ 1  2 -4 -4  5]


In [48]:
arr1 # 2d array

array([[4, 5, 6],
       [7, 8, 9]])

In [49]:
arr1.T # transpose of 2d array

array([[4, 7],
       [5, 8],
       [6, 9]])

In [54]:
print(arr2)
print(arr)
arr.dot(arr2) # array element product

[-4  1  2  5 30]
[ 1  2 -4 -4  5]


120

In [67]:
arr.resize((2,2), refcheck=False) # changing array shape 
# if given size is short or long then extra data will be lost or entered as 0
arr 

array([[ 1,  2],
       [-4, -4]])

In [72]:
ar = np.array([[2,3], [3,3]])
ar.dot(arr) # matrix multiplication for 2d array

array([[-10,  -8],
       [ -9,  -6]])

In [69]:
arr2.reshape(1,5) # changing array shape
# data != prod(shape size) then it gives an error 

array([[-4,  1,  2,  5, 30]])

In [83]:
# operators on array
print(f' arr  :\n{arr}')
print(f'\nar  :\n{ar}\n')
print(f'arr + ar : \n {arr + ar}\n')
print(f'arr - ar : \n {arr - ar}\n')
print(f'arr * ar : \n {arr * ar}\n')
print(f'arr / ar : \n {arr / ar}\n')


 arr  :
[[ 1  2]
 [-4 -4]]

ar  :
[[2 3]
 [3 3]]

arr + ar : 
 [[ 3  5]
 [-1 -1]]

arr - ar : 
 [[-1 -1]
 [-7 -7]]

arr * ar : 
 [[  2   6]
 [-12 -12]]

arr / ar : 
 [[ 0.5         0.66666667]
 [-1.33333333 -1.33333333]]



In [84]:
arr * 2

array([[ 2,  4],
       [-8, -8]])

In [85]:
arr+2

array([[ 3,  4],
       [-2, -2]])

In [86]:
arr - 3

array([[-2, -1],
       [-7, -7]])

In [87]:
arr / 4

array([[ 0.25,  0.5 ],
       [-1.  , -1.  ]])

In [88]:
arr % 5

array([[1, 2],
       [1, 1]])

In [93]:
arr.astype(np.int32) # change data type into given & return new array

array([[ 1,  2],
       [-4, -4]], dtype=int32)

In [102]:
arr.conjugate()

array([[-4294967296,          -1],
       [         -4,          -4]])

In [104]:
arr[0] = 9
arr.conj()

array([[ 9,  9],
       [-4, -4]])

In [109]:
arr2.compress(arr2 < 0) # condition on arrays (only 1D)

array([-4])

In [114]:
np.argwhere(arr2 >= 0)


array([[ 1],
       [ 2],
       [ 5],
       [30]])

In [9]:
a = np.array([1,2,3]) # 
b = a[::-1].copy()
b

array([3, 2, 1])